blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: mailto:security@opensecops.org
    about: Please report security vulnerabilities directly to our security team by email
  - name: Documentation Issue
    url: https://github.com/OpenSecOps-Org/.github/issues/new?labels=documentation
    about: Report issues with documentation
  - name: General Question or Discussion
    url: https://github.com/OpenSecOps-Org/.github/discussions
    about: Please ask and answer questions here